services:
  identity:
    image: ${IDENTITY_IMAGE:-cortesa/link-wars-identity:latest}
    networks:
      - link-wars-net
    restart: unless-stopped

  cashier:
    build:
      context: .
      dockerfile: services/cashier/Dockerfile
      target: development
    volumes:
      - ./services/cashier/src:/app/services/cashier/src
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - identity
    networks:
      - link-wars-net
    restart: unless-stopped

  game-server:
    build:
      context: .
      dockerfile: services/game-server/Dockerfile
      target: development
    volumes:
      - ./services/game-server/src:/app/services/game-server/src
    environment:
      - PORT=2567
    ports:
      - "2567:2567"
    depends_on:
      - identity
    networks:
      - link-wars-net
    restart: unless-stopped

  client-web:
    build:
      context: .
      dockerfile: services/client-web/Dockerfile
      target: development
    volumes:
      - ./services/client-web:/app/services/client-web
    ports:
      - "5173:5173"
    depends_on:
      - game-server
    networks:
      - link-wars-net
    restart: unless-stopped

networks:
  link-wars-net:
    driver: bridge

volumes:
  db-data:
  redis-data:
